apiVersion: v1
kind: Secret
metadata:
  name: evently-secrets
  namespace: evently
type: Opaque
data:
  # have added dummy values, in prod we should replace this
  DB_URL: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQHBvc3RncmVzOjU0MzIvZXZlbnRseV9kYj9zc2xtb2RlPWRpc2FibGU=
  REDIS_URL: cmVkaXM6Ly9yZWRpczozNjM3OS8=
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: evently-config
  namespace: evently
data:
  PORT: "8080"
  ENV: "production"
  